version: '3'
services:
  my-react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3100:3000"
    volumes:
      - /app/node_modules
      - .:/app
  react-test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
    volumes:
      - /app/node_modules
      - .:/app
